version: "3.4"

services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
      target: app_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    restart: unless-stopped
    depends_on:
      - vuejs
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
  caddy:
    build:
      context: ./
      dockerfile: ./docker/caddy/Dockerfile
      target: app_caddy
    depends_on:
      - vuejs
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
    restart: unless-stopped
    volumes:
      - vue_socket:/var/run/docker.sock
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      - target: 8010
        published: ${HTTP_PORT:-8010}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
  vuejs:
    build:
      context: ./
      dockerfile: ./docker/vuejs/Dockerfile
      target: dev-envs
    volumes:
      - vue_socket:/var/run/docker.sock
# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

volumes:
  php_socket:
  caddy_data:
  caddy_config:
  vue_socket:
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
